### PR TITLE
Add NSMutableDictionary class

### PR DESCRIPTION
**Pull request by programmingkidx**
Adds the NSMutableDictionary class. Here is a little test program to see it work:

```
package main

import "github.com/progrium/macdriver/core"
import "fmt"

func main() {
	md := core.NSMutableDictionary_Alloc().Init()
	md.SetObjectForKey(core.NSString_FromString("love"), core.NSString_FromString("Password"))
	md.SetObjectForKey(core.NSString_FromString("8"), core.NSString_FromString("numberOfLives"))
	md.SetObjectForKey(core.NSString_FromString("MacDriver"), core.NSString_FromString("Best Go to Objective-C project"))
	fmt.Println("Value:", md)
}
```

### CODE REVIEW

**Comment by tmc** [comment]
this needs a `NSMutableDictionary.go` wrapper file

**Comment by programmingkidx** [comment]
Oops. Good catch.

**Comment by programmingkidx** [comment]
Will make a new pull request.

**Comment by tmc** [comment]
why not push a new commit with that file?

**Comment by programmingkidx** [comment]
Sorry but I don't know git that well 😬

**Pull request closed without merging**
