### PR TITLE
[wip] schema generation tool

### PR DESCRIPTION
**Pull request by progrium**
This PR introduces a new tool that can parse Apple documentation pages for a class and produce a partial schema in JSON. It's intended to aid in the eventual code generation of wrapper types. Since Apple API schemas don't really exist other than hard-to-find, sometimes outdated, and otherwise crufty bridgesupport files, I dreamed of just scraping the documentation. At the very least, it can provide stubs that include generated doc comments with links to actual Apple API docs as we've been starting to do by hand.

Schemas are useful for all sorts of things, so separating schema generation from code generation increases the value of what we're providing here. Although it doesn't yet know type and other metadata for class members, all that data can be parsed from their individual pages, which this does pull the links for. 

I've written and tried against NSWindow (and now many others), which is our biggest class. The file `schema/NSWindow.json` was generated with `go run . "https://developer.apple.com/documentation/appkit/nswindow?language=objc"` from the `tools/schema` directory.

It's using [chromedp](github.com/chromedp/chromedp) instead of something lighter and more ergonomic, but Apple's site doesn't seem to render without Javascript. That said, I'm surprised what could be done with just 150 lines, it's just a little awkward.

### CODE REVIEW

**Comment by progrium** [comment]
Tried it on a handful of other classes and it Just Works. It now ignores deprecated members. Also noted that properties can be type properties, which it can't distinguish at this level. Might go back to dumping all topics into a Topics field to then parse into appropriate schema parts (instance method, type property, etc), though I'm not sure if I should serialize Topics (esp recursively) since that would introduce a lot of redundancy, though it might be nice to have?

**Comment by progrium** [comment]
Would love it if somebody could write a declaration parser as that's a huge part of the rest of the schema data for members. Examples:
`@interface NSMenu : NSObject`
`- (NSRect)convertRectToBacking:(NSRect)rect;`
`+ (BOOL)menuBarVisible;`
`+ (void)setMenuBarVisible:(BOOL)visible;`
`- (NSColor *)blendedColorWithFraction:(CGFloat)fraction 
                              ofColor:(NSColor *)color;`
`- (void)resetCursorRects;`
`- (instancetype)initWithContentRect:(NSRect)contentRect 
                          styleMask:(NSWindowStyleMask)style 
                            backing:(NSBackingStoreType)backingStoreType 
                              defer:(BOOL)flag;`
`@property CGFloat alphaValue;`
`@property(getter=isVisible, readonly) BOOL visible;`
`@property(class, readonly, strong) NSStatusBar *systemStatusBar;`
`- (void)removeStatusItem:(NSStatusItem *)item;`

**Comment by blacktop** [comment]
I have a tool that pulls all these out of the dyld_shared_cache so you'd get public and private frameworks. https://github.com/blacktop/ipsw 

The tools not well "tested" but it should be very easy to output these JSON, but then you'd have to map it to the docs via your other parsing?

$ ipsw download -v 14.4.2 -d iPhone13,3 
$ ipsw extract -d iPhone*.ipsw
$ ipsw dyld macho iPhone*/dyld* --all --objc -V

**Comment by progrium** [comment]
@blacktop ah this is very cool. Your `ipsw` continues to surprise! I'll try it out to see if it can be used for constants/global values since I don't believe I can get those via libobjc and would be more of a pain to consistently pull from their docs. Will definitely see how `ipsw` can augment stuff here. thanks for the tip!

**Comment by flexzuu** [comment]
I would be willing to tackle the parser I was thinking of building something with `goyacc` but then found 
https://github.com/DanielMSchmidt/objective-c-parser/blob/master/index.js and think it might be more practical to just port this to go. What do you think?

**Comment by progrium** [comment]
@flexzuu the scope is so small a tool like goyacc might be overkill, and porting from JS is definitely possible but won't be very idiomatic. if it were me (which it often is) i'd make a simple lexer/parser a la https://blog.gopheracademy.com/advent-2014/parsers-lexers/ or https://talks.golang.org/2011/lex.slide#1

**Comment by flexzuu** [comment]
> @flexzuu the scope is so small a tool like goyacc might be overkill, and porting from JS is definitely possible but won't be very idiomatic. if it were me (which it often is) i'd make a simple lexer/parser a la https://blog.gopheracademy.com/advent-2014/parsers-lexers/ or https://talks.golang.org/2011/lex.slide#1

I started with a simple regex based parsing for now. I think this might be enough. Or at least a good base to understand the grammar etc. I will send a link with the code once it can get all the examples you posted above. The provided resources look nice though and will help me to get my first parser going if we decide the regex approach is not what we want.

**Comment by flexzuu** [comment]
Here is my first draft https://github.com/flexzuu/macdriver/tree/flexzuu/parser/objc/declaration

**Comment by progrium** [comment]
That's awesome. Looks like we were working in parallel. I took inspiration from your implementation for a few things. Mine is not as concise but a bit more extensible and arguably more idiomatic. In theory faster, though speed is not a huge thing here.

**Pull request merged**
