### PR TITLE
gen: Improve identifier naming, quality of generated code

### LINKED ISSUE #119: Change generator to stop translating colon to underscore
Currently the generator translates the colon in an objective-c method into an underscore. This leads to the undesirable result of methods with names that end with an underscore (e.g. ObjectForKey_() instead of ObjectForKey() ). I suggest that these rules be implemented when generating Go function names:

- For class methods we use the format Classname_methodname(). There are times when the method name is shorted, like when the last part of the class name contains the first part the method name (e.g. NSArray_WithObjects() instead of NSArray_arrayWithObjects() ). I do agree with that format but I still think it is a good idea to also include a method that includes the full method name. It is a lot less confusing for new people. Of course the shorted method could lead to confusion as to  which objective-c method it wraps, so maybe be should remove all these shorten methods and replace them with more proper names.

- Instance methods should use the Go format of using uppercase for the first letter of each word. I don't think we need underscores at all. For example instead of the NSUserDefaults' method SetObject_ForKey() it should be SetObjectForKey(). It looks more Go-like (and pretty 😁).

### PR DESCRIPTION
**Pull request by tmc**
Fixes #119, this omits trailing underscores from generated identifiers and adopts new more Go-idiomatic naming.

### CODE REVIEW

**Comment by tmc** [comment]
This greatly improves the ergonomicsd of the generated code and godoc.

compare

Screenshot 2023-07-05 at 2 35 34 PM

with

Screenshot 2023-07-05 at 2 35 37 PM

**Comment by progrium** [comment]
Looks good so far. Much nicer. Don't know if people actually want lowercase class methods after underscore, but given we convert method names everywhere else to capitalized it seems like they should be capitalized too, even if they technically don't have to be. Thoughts?

**Comment by tmc** [comment]
> Looks good so far. Much nicer. Don't know if people actually want lowercase class methods after underscore, but given we convert method names everywhere else to capitalized it seems like they should be capitalized too, even if they technically don't have to be. Thoughts?

Open to that, trying to do this iteratively and I think this merits inclusion as-is while we iterate on naming scheme.

**Comment by mgood** [comment]
IIRC the trailing underscores is something I saw done in PyObjC. I know it looks a little weird, but without it I think there can be selector conflicts where you have one with and one without an argument.

**Comment by tmc** [comment]
> IIRC the trailing underscores is something I saw done in PyObjC. I know it looks a little weird, but without it I think there can be selector conflicts where you have one with and one without an argument.

Yeah we have an example in/with the webkit reload method

**Comment by progrium** [comment]
Looks good. Fairly breaking change though. Should we cut a release before merging?

**Comment by programmingkidx** [comment]
@progrium As for the question of whether to capitalize the first letter of a method's name when dealing with a class method. Objective-C doesn't do it. Go does like camel case. But Go functions don't usually have an underscore to them. If I had to vote between these options:
- NSEvent_alloc()
- NSEvent_Alloc()
- NSEventAlloc()

I would probably pick NSEvent_alloc(). It seems like less work to have to write it out like this.

As for cutting a release, please do so. The more release numbers there are the easier it to tell what changes have been made between releases.

**Comment by programmingkidx** [comment]
@tmc Thank you for the changes. I really like how the return type of a function is on the same line as the func statement. This is so much easier to read than how it was before.

**Comment by tmc** [comment]
we're doing `NSEvent_Alloc` for consistency

**Comment by programmingkidx** [comment]
@tmc I can learn to live with that.

**Pull request merged**
