### PR TITLE
Example of TableView

### PR DESCRIPTION
**Pull request by corruptmemory**
- Shows how to create a TableView
- Dynamically updates data in the table

### CODE REVIEW

**Comment by corruptmemory** [comment]
Addresses #214

**Comment by progrium** [comment]
Looks good!

Also looks like we missed a delegate builder. I guess because we only generate those if the name ends with Delegate, since it could sometimes be a Protocol for something else. But maybe we should just make delegate builders for every protocol anyway?

**Comment by Charliego3** [comment]
@corruptmemory Could you please provide an example of OutlineView? I tried not to display the content anyway, thank you very much!

**Comment by progrium** [comment]
@Charliego3 I'm not sure OutlineView was something they were interested in, but if you'd like to make a separate issue requesting somebody make an OutlineView example, that might be more fruitful.

**Comment by Charliego3** [comment]
> @Charliego3 I'm not sure OutlineView was something they were interested in, but if you'd like to make a separate issue requesting somebody make an OutlineView example, that might be more fruitful. 

OK，Thanks.

**Pull request merged**
